[package]
name = "forge-web-ui"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]   # required for wasm

[dependencies]
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["Window","Document","HtmlElement"] }
console_error_panic_hook = "0.1"
