[package]
name = "forge-util"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
walkdir = "2.5"
ignore = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
camino = "1.1"
