[package]
name = "forge-proc"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
forge-template = { path = "../forge-template" }
serde_json = "1"
mustache = "0.9.0"
anyhow = "1.0.99"
serde_yaml = "0.9.34+deprecated"